server:
  port: 8001
  servlet:
    context-path: /job-api

spring:
  application:
    name: alas-job-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  sql:
    init:
      encoding: UTF-8
      data-locations: classpath:data.sql
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: assistant-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "kr.alas.job.service.domain.model"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


springdoc:
  api-docs:
    path: /api-docs
    enabled: true
    resolve-schema-properties: true
    groups:
      enabled: true
  cache:
    disabled: true
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    operations-sorter: alpha
    tags-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /**
  packages-to-scan: kr.alas.job.service.domain
